# Generated by Django 5.1.5 on 2025-01-22 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_gymclass_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackerentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trackerentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets_reps', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('tracker_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='authapp.trackerentry')),
            ],
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mood', models.CharField(max_length=50)),
                ('energy_level', models.CharField(max_length=50)),
                ('tracker_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to='authapp.trackerentry')),
            ],
        ),
    ]
