# Generated by Django 5.1.5 on 2025-01-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_trackerentry_user_alter_trackerentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerentry',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
